version: "3"

services:
  demo:
    image: maven:3
    restart: always
    command: mvn spring-boot:run
    volumes:
      - .:/opt/demo
      - m2:/root/.m2
    working_dir: /opt/demo
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      TZ: Asia/Tokyo

  postgres:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  m2:
    external: true
  pgdata: